/* Brief Builder — real content pulled from The Brief Bible (Notion).
   SECTIONS: the ordered brief-database sections.
   MODULES:  pre-generated workspace info you can drop into a brief.
   TEXT_FORMATS: block formats for the writing surface.
   VISUAL_FORMATS: the ad-format library (the "Visual Format" section). */

window.SECTIONS = [
  { n: 1,  name: "Brand",             icon: "sparkles", status: "planned",
    what: "The belief. Your mission and USPs, the reasons this brand is worth backing. Reads persuasively, like a good sales letter.",
    why:  "Creators convert harder when they believe in what they're repping. Audiences tell the difference between a product being flogged and a brand being backed." },
  { n: 2,  name: "The Offer",         icon: "tag", status: "planned",
    what: "The deal. What the creator gets in return: money, gift in kind, or a stack of both. The plain answer to \u201cwhat's in it for me.\u201d",
    why:  "This is the line a creator decides on. Bury it and they pass. Creators run a business and need to see the return before they give you their time." },
  { n: 3,  name: "Audience / Customer", icon: "users", status: "planned",
    what: "The person on the other end of the camera. Who they are, what they care about, the problem in their life, how the creator should hold themselves toward them.",
    why:  "A creator who can picture exactly who they're talking to makes content that lands as a recommendation, not an advert." },
  { n: 4,  name: "Product / Feature", icon: "package", status: "planned",
    what: "The product said plainly. What it is, what it does, and the handful of things it's known for. The creator's factual reference.",
    why:  "A creator can't talk credibly about something they don't understand. This is the ground truth they build from." },
  { n: 5,  name: "Creator Benefits",  icon: "gift", status: "planned",
    what: "Why the creator personally wins. Money case first for commission-led creators; the softer perks and content lift for fee-led creators.",
    why:  "A creator sizing up a brief needs to believe it's worth their effort. Land that belief and they're in." },
  { n: 6,  name: "Deliverables",      icon: "check-square", status: "planned",
    what: "What to make. The number, the specs, how it's delivered, and the timing. The unambiguous definition of done.",
    why:  "Vague deliverables are where briefs fall apart. A creator can only hit the target if they can see it." },
  { n: 7,  name: "Hook",              icon: "zap", status: "planned",
    what: "The opening three seconds, built as three components that fire together: on-screen caption, visual action, and first spoken words. Options to test.",
    why:  "Three seconds decides whether the rest gets watched. The single biggest lever on whether content performs." },
  { n: 8,  name: "Talking Points",    icon: "message-square", status: "planned",
    what: "Talking Points and Script are the same slot filled two ways, never both. Who leads sets the default; format adjusts it.",
    why:  "Give creators the angles that matter and you get content that's specific, credible, and on-message, without killing the authenticity." },
  { n: 9,  name: "Script",            icon: "file-text", status: "planned",
    what: "The brand-led counterpart to Talking Points. Brand-led means you own the words and the creator performs them.",
    why:  "For brand-led content, a storyboard puts the beats in order and scripts the lines that have to land word for word." },
  { n: 10, name: "Visual Format",     icon: "layout", status: "planned", special: "visual",
    what: "The visual format: testimonial, demo, us vs them, before and after, and more.",
    why:  "The format shapes how the whole piece is shot. Pick the one that fits the funnel stage and the product." },
  { n: 11, name: "Examples",          icon: "image", status: "planned",
    what: "The reference clips. Top-performing ads, content you've reviewed, or swipe files, handed over as the standard to hit.",
    why:  "Telling a creator what you want only goes so far; showing them lands it. A couple of strong references set the bar." },
  { n: 12, name: "Props",             icon: "box", status: "planned",
    what: "The items the creator needs on hand to film: the product and its packaging, plus any props the concept calls for.",
    why:  "A clear props list means the creator gathers everything first, so every shot the storyboard needs can be filmed." },
  { n: 13, name: "Production Notes",  icon: "video", status: "planned",
    what: "The filming instructions. Device, stabilisation, lighting, background, how to handle the product, length and takes.",
    why:  "The same script shot on a wobbly phone in bad light comes back unusable. These notes set the technical floor." },
  { n: 14, name: "Guidelines",        icon: "shield-check", status: "planned",
    what: "The creator's dos and don'ts, generated from the thresholds and review agents mapped to the chosen format.",
    why:  "Because it's generated from the same settings Brieflee checks, the creator's instructions and your quality bar are the same thing." },
  { n: 15, name: "Usage Rights",      icon: "scale", status: "planned",
    what: "The rights grant. Who can use the content, on which channels, and for how long. Forks by who owns the content.",
    why:  "Rights left vague cause disputes and block the paid amplification that makes good content compound." },
  { n: 16, name: "Submissions",       icon: "upload-cloud", status: "planned",
    what: "The hand-in method. How the creator gets finished content to the brand: manually as a file, or through Brieflee as a checked link.",
    why:  "A clear route means the work arrives in the right format, in the right place, ready to review." },
  { n: 17, name: "Contact / Community", icon: "life-buoy", status: "planned",
    what: "The way in. Where to go with a question, and how to join the ongoing creator group, so the relationship carries past this one video.",
    why:  "This turns a one-off job into a lasting relationship, growing their content and their sales video by video." },
  { n: 18, name: "Creator Info",      icon: "user", status: "live",
    what: "The creator's own details carried into the brief \u2014 name, handle, channel.",
    why:  "Personalises the brief and links it to the right creator record." },
  { n: 19, name: "Extra",             icon: "plus-circle", status: "live",
    what: "A free block for anything the standard sections don't cover.",
    why:  "Every brief has a one-off. This is where it goes." },
];

window.MODULES = [
  { name: "Product Info",     icon: "info",       blueprint: true,  desc: "Add product information" },
  { name: "Feature Info",     icon: "list",       blueprint: true,  desc: "Add feature info" },
  { name: "Content Style",    icon: "star",       blueprint: true,  desc: "Add content style" },
  { name: "Target Audience",  icon: "target",     blueprint: true,  desc: "Add target audience" },
  { name: "Format",           icon: "file",       blueprint: true,  desc: "Add format information" },
  { name: "Concepts",         icon: "pen-tool",   blueprint: true,  desc: "Add a concept from your workspace" },
  { name: "Community",        icon: "users-round",blueprint: false, desc: "WhatsApp, Discord, Lark, Slack, Telegram, ambassador & affiliate pages" },
  { name: "Contact",          icon: "mail",       blueprint: false, desc: "Website, staff email, social media handles" },
  { name: "Content Reference",icon: "zap",        blueprint: false, desc: "Reference content from top ads, reviewed or swiped content in your library" },
  { name: "Asset Links",      icon: "link",       blueprint: false, desc: "Add links to assets" },
  { name: "Channel",          icon: "rectangle",  blueprint: false, desc: "Add channel information" },
  { name: "Media",            icon: "image",      blueprint: false, desc: "Upload images and video" },
  { name: "Embed",            icon: "code",       blueprint: false, desc: "Embed a website, video, preview, and more" },
  { name: "Attach Files",     icon: "paperclip",  blueprint: false, desc: "Attach other files" },
  { name: "Music",            icon: "music",      blueprint: false, desc: "Add music information" },
  { name: "Output Sizes",     icon: "crop",       blueprint: false, desc: "Add output size details" },
  { name: "Variant Info",     icon: "layers",     blueprint: false, desc: "Add variant details" },
  { name: "Thresholds",       icon: "sliders",    blueprint: false, desc: "Score thresholds Brieflee checks against" },
  { name: "Review Agents",    icon: "bot",        blueprint: false, desc: "AI agents that review submitted content" },
];

window.TEXT_FORMATS = [
  { group: "Format", items: [
    { name: "Heading",       icon: "heading",      desc: "Add a section heading" },
    { name: "Bullet List",   icon: "list",         desc: "Unordered list of items" },
    { name: "Numbered List", icon: "list-ordered", desc: "Ordered, numbered list" },
    { name: "Task List",     icon: "check-square",  desc: "Checklist of to-do items" },
    { name: "Blockquote",    icon: "quote",        desc: "Set text apart as a quote" },
    { name: "Code Block",    icon: "code",         desc: "Formatted block of code" },
  ]},
  { group: "Insert", items: [
    { name: "Table",           icon: "table",       desc: "Table for structured data" },
    { name: "Horizontal Rule", icon: "minus",       desc: "A horizontal divider line" },
    { name: "3-Column Block",  icon: "columns",     desc: "Three side-by-side columns" },
    { name: "Embed Block",     icon: "code",        desc: "Embed a link, video or preview" },
  ]},
];

window.CHANNELS = [
  { name: "Facebook",  color: "#1877F2", img: "https://res.cloudinary.com/dchroynzv/image/upload/brieflee_icon_facebook-logo-3d-transparent_2026-05.png" },
  { name: "Instagram", color: "#E1306C", img: "https://res.cloudinary.com/dchroynzv/image/upload/brieflee_icon_instagram-logo-3d-transparent_2026-05.png" },
  { name: "TikTok",    color: "#010101", img: "https://res.cloudinary.com/dchroynzv/image/upload/brieflee_icon_tiktok-logo-3d-transparent_2026-05.png" },
  { name: "YouTube",   color: "#FF0000", img: "https://res.cloudinary.com/dchroynzv/image/upload/brieflee_icon_youtube-shorts-logo-3d-transparent_2026-05.png" },
  { name: "LinkedIn",  color: "#0A66C2", img: "https://res.cloudinary.com/dchroynzv/image/upload/brieflee_app-icon_linkedin-share-3d-transparent_2026-06.png" },
];

window.WORKSPACE = {
  products: [
    { name: "Volcanic Roller",  sub: "Oil-absorbing stone \u00b7 \u00a324" },
    { name: "Roller + Case set", sub: "Roller + travel case \u00b7 \u00a332" },
    { name: "Mini Roller",       sub: "Pocket size \u00b7 \u00a318" },
  ],
  features: [
    { name: "Reusable stone",        sub: "Replaces disposable blotting papers" },
    { name: "Makeup-safe finish",    sub: "Lifts oil without smudging makeup" },
    { name: "Washable, lasts months", sub: "Rinse and it's like new" },
  ],
};

// Blueprint assets scoped to the chosen focus (product/feature).
window.blueprintFor = function (focus) {
  return {
    contentStyle: "Warm, honest, first-person. Real skin, real results, never clinical.",
    audience: "Skincare and makeup lovers, 20\u201335, who go shiny by midday and have quietly put up with it.",
    concepts: [
      { name: "The Switch", desc: "Ditch the blotting papers, one reusable stone does it better." },
      { name: "Matte at 3pm", desc: "The midday shine, and the one tool that fixed it." },
      { name: "Magic trick", desc: "Watch the oil lift off the stone in real time." },
    ],
    formats: ["Testimonial", "Demo", "Before & After"],
    hooks: [
      "This removes oil without ruining your makeup.",
      "If your face gets shiny by noon, you need this.",
      "I stopped using blotting papers because of this.",
    ],
    ctas: [
      "Use my code for 15% off your first roller.",
      "Link in bio, it ships free.",
      "If you're still blotting with loo roll, just try this.",
    ],
  };
};

// Hosted brand icons, keyed by section/module name. Rail uses these when present,
// falling back to the lucide set. Delete this object to revert to lucide everywhere.
window.SECTION_ICONS = {
  "Brand": "https://res.cloudinary.com/dchroynzv/image/upload/brieflee_help-icon_workspace-checkmark-badge-wavy-edge-approved-transparent_2026-05.png",
  "The Offer": "https://res.cloudinary.com/dchroynzv/image/upload/brieflee_help-icon_billing-wallet-cash-green-money-bills-transparent_2026-05.png",
  "Audience / Customer": "https://res.cloudinary.com/dchroynzv/image/upload/brieflee_help-icon_core-concepts-bullseye-target-with-blue-arrow-transparent_2026-05.png",
  "Product / Feature": "https://res.cloudinary.com/dchroynzv/image/upload/brieflee_icon_diamond-shape-icon-transparent_2026-05.png",
  "Creator Benefits": "https://res.cloudinary.com/dchroynzv/image/upload/brieflee_help-icon_affiliate-trophy-cup-blue-sticker-transparent_2026-05.png",
  "Deliverables": "https://res.cloudinary.com/dchroynzv/image/upload/brieflee_icon_simple-bold-lined-to-do-list-transparent_2026-05.png",
  "Hook": "https://res.cloudinary.com/dchroynzv/image/upload/brieflee_help-icon_troubleshoot-lightning-bolt-sticker-blue-transparent_2026-05.png",
  "Talking Points": "https://res.cloudinary.com/dchroynzv/image/upload/brieflee_icon_flat-hip-condenser-microphone-sticker-transparent_2026-05.png",
  "Script": "https://res.cloudinary.com/dchroynzv/image/upload/brieflee_icon_simple-lined-clipboard-with-pen-transparent_2026-05.png",
  "Visual Format": "https://res.cloudinary.com/dchroynzv/image/upload/brieflee_icon_blue-movie-clapper-illustration-transparent_2026-05.png",
  "Examples": "https://res.cloudinary.com/dchroynzv/image/upload/brieflee_icon_simple-lined-book-and-magnifying-glass-transparent_2026-05.png",
  "Props": "https://res.cloudinary.com/dchroynzv/image/upload/brieflee_icon_simple-lined-file-folder-bag-transparent_2026-05.png",
  "Production Notes": "https://res.cloudinary.com/dchroynzv/image/upload/brieflee_icon_smartphone-in-tripod-flat-illustration-transparent_2026-05.png",
  "Guidelines": "https://res.cloudinary.com/dchroynzv/image/upload/brieflee_help-icon_brief-and-projects-folder-with-white-tab-transparent_2026-05.png",
  "Usage Rights": "https://res.cloudinary.com/dchroynzv/image/upload/brieflee_icon_padlock-sticker-blue-transparent_2026-05.png",
  "Submissions": "https://res.cloudinary.com/dchroynzv/image/upload/brieflee_icon_send-paper-plane-periwinkle-transparent_2026-06.png",
  "Contact / Community": "https://res.cloudinary.com/dchroynzv/image/upload/brieflee_help-icon_members-speech-bubble-profile-icon-with-count-one-transparent_2026-05.png",
  "Creator Info": "https://res.cloudinary.com/dchroynzv/image/upload/brieflee_help-icon_team-id-badge-card-with-profile-photo-transparent_2026-05.png",
  "Extra": "https://res.cloudinary.com/dchroynzv/image/upload/brieflee_icon_blue-multiple-stars-transparent_2026-05.png",
  "Content Reference": "https://res.cloudinary.com/dchroynzv/image/upload/brieflee_icon_simple-lined-book-and-magnifying-glass-transparent_2026-05.png",
  "Asset Links": "https://res.cloudinary.com/dchroynzv/image/upload/brieflee_icon_electric-plug-icon-transparent_2026-05.png",
  "Channel": "https://res.cloudinary.com/dchroynzv/image/upload/brieflee_help-icon_notifications-megaphone-loudspeaker-blue-transparent_2026-05.png",
  "Attach Files": "https://res.cloudinary.com/dchroynzv/image/upload/brieflee_icon_docs-file-icon-transparent_2026-05.png",
  "Embed": "https://res.cloudinary.com/dchroynzv/image/upload/brieflee_icon_simple-bold-lined-computer-transparent_2026-05.png",
  "Media": "https://res.cloudinary.com/dchroynzv/image/upload/brieflee_icon_watch-video-play-button-transparent_2026-05.png",
  "Music": "https://res.cloudinary.com/dchroynzv/image/upload/brieflee_icon_flat-hip-headphones-sticker-transparent_2026-05.png",
  "Output Sizes": "https://res.cloudinary.com/dchroynzv/image/upload/brieflee_icon_simple-bold-lined-pie-chart-transparent_2026-05.png",
  "Variant Info": "https://res.cloudinary.com/dchroynzv/image/upload/brieflee_icon_retro-colorful-shape-transparent_2026-05.png",
  "Thresholds": "https://res.cloudinary.com/dchroynzv/image/upload/brieflee_icon_flat-hip-timer-stopwatch-sticker-transparent_2026-05.png",
  "Review Agents": "https://res.cloudinary.com/dchroynzv/image/upload/brieflee_icon_review-eyes-glass-3d-clearer-periwinkle-transparent_2026-07.png",
  "Contact": "https://res.cloudinary.com/dchroynzv/image/upload/brieflee_help-icon_members-speech-bubble-profile-icon-with-count-one-transparent_2026-05.png",
  "Concepts": "https://res.cloudinary.com/dchroynzv/image/upload/brieflee_help-icon_workspaces-lightbulb-with-rays-ideas-transparent_2026-05.png",
  "Content Style": "https://res.cloudinary.com/dchroynzv/image/upload/brieflee_icon_trendy-flat-paint-palette-sticker-transparent_2026-05.png",
  "Format": "https://res.cloudinary.com/dchroynzv/image/upload/brieflee_icon_blue-movie-clapper-illustration-transparent_2026-05.png",
  "Product Info": "https://res.cloudinary.com/dchroynzv/image/upload/brieflee_icon_diamond-shape-icon-transparent_2026-05.png",
  "Target Audience": "https://res.cloudinary.com/dchroynzv/image/upload/brieflee_help-icon_core-concepts-bullseye-target-with-blue-arrow-transparent_2026-05.png",
  "Feature Info": "https://res.cloudinary.com/dchroynzv/image/upload/brieflee_icon_diamond-shape-icon-transparent_2026-05.png",
  "Community": "https://res.cloudinary.com/dchroynzv/image/upload/brieflee_help-icon_members-speech-bubble-profile-icon-with-count-one-transparent_2026-05.png",
};

window.VISUAL_FORMATS = [
  { name: "Testimonial",  emoji: "\uD83E\uDD29", funnel: "Solution \u2192 Product", desc: "A real customer telling their story: the pain before, what changed when the product showed up." },
  { name: "Demo",         emoji: "\u2705", funnel: "Solution \u2192 Product", desc: "Show it working. Hands using the product, the result happening in real time." },
  { name: "Before & After", emoji: "\uD83D\uDD04", funnel: "Problem \u2192 Product", desc: "One frame of the before, one of the after. The space between is your product." },
  { name: "How To",       emoji: "\uD83D\uDEE0\uFE0F", funnel: "Solution \u2192 Product", desc: "Walk the viewer through it, step by step. The product is the tool inside the lesson." },
  { name: "Yapper",       emoji: "\uD83D\uDDE3\uFE0F", funnel: "Problem \u2192 Solution", desc: "Creator talking straight to camera. No props, no cuts, just face, words and energy." },
  { name: "POV",          emoji: "\uD83D\uDC40", funnel: "Unaware \u2192 Problem", desc: "Shot from the viewer's perspective, as if it were their hands, their morning, their day." },
  { name: "Founder",      emoji: "\uD83D\uDC64", funnel: "Problem \u2192 Solution", desc: "You, on camera. Why you built this and what was broken about every other option." },
  { name: "Listicle",     emoji: "\uD83D\uDCDD", funnel: "Problem \u2192 Solution", desc: "Numbered and snappy. \u20183 reasons I switched\u2019, \u20185 things I wish I knew\u2019." },
  { name: "Expert Explainer", emoji: "\uD83E\uDDE0", funnel: "Unaware \u2192 Problem", desc: "An authority explains the product or problem. Credibility lives in who's saying it." },
  { name: "Unboxing",     emoji: "\uD83D\uDCE6", funnel: "Solution \u2192 Product", desc: "Opening the box on camera: packaging, paper, the product in its first moment." },
  { name: "Try-On",       emoji: "\uD83D\uDC57", funnel: "Solution \u2192 Product", desc: "Trying the product on, on camera. The viewer starts imagining it on themselves." },
  { name: "Transformation", emoji: "\uD83E\uDD8B", funnel: "Problem \u2192 Product", desc: "The change on camera in one continuous take. Shows the journey, not just the endpoints." },
  { name: "Skit",         emoji: "\uD83C\uDFAD", funnel: "Unaware", desc: "A mini-story with characters. Comedy as the wrapper, product as the punchline." },
  { name: "Street Interview", emoji: "\uD83C\uDFA4", funnel: "Unaware \u2192 Problem", desc: "Man-on-the-street. A creator with a mic, real people, real answers." },
  { name: "Review",       emoji: "\u2B50", funnel: "Solution \u2192 Product", desc: "A real review read aloud or shown over footage. The words aren't yours." },
  { name: "Comment Response", emoji: "\uD83D\uDCAC", funnel: "Problem \u2192 Product", desc: "Frame the ad as a reply to a real comment. Feels native, feels honest." },
  { name: "Greenscreen",  emoji: "\uD83D\uDFE2", funnel: "Problem \u2192 Product", desc: "You on camera with a screenshot, article or review behind you." },
  { name: "Problem Agitation", emoji: "\uD83D\uDE21", funnel: "Problem Aware", desc: "Show the problem at its worst. Make the viewer feel the pain before the way out." },
  { name: "Educational",  emoji: "\uD83C\uDF93", funnel: "Unaware \u2192 Problem", desc: "Teach something they didn't know. Not \u2018buy this\u2019 \u2014 \u2018here's what's happening\u2019." },
  { name: "Podcast",      emoji: "\uD83C\uDF99\uFE0F", funnel: "Unaware \u2192 Problem", desc: "Two people, mics, jump cuts. Looks like a clip pulled from a longer episode." },
  { name: "Trend",        emoji: "\uD83D\uDD25", funnel: "Unaware", desc: "A current trend used the way the platform uses it. Speed beats polish." },
  { name: "Meme",         emoji: "\uD83E\uDD23", funnel: "Unaware", desc: "A current meme, used the way it's actually used. Your product where the punchline lands." },
  { name: "Screen Recording", emoji: "\uD83D\uDCBB", funnel: "Solution \u2192 Product", desc: "Phone or computer screen recorded straight. App walkthroughs, reviews, comparisons." },
  { name: "Influencer Endorsement", emoji: "\uD83D\uDC69\u200D\uD83D\uDCBC", funnel: "Solution \u2192 Product", desc: "A creator your audience follows, with your product in their hands." },
  { name: "Celebrity",    emoji: "\u2B50", funnel: "Product \u2192 Most Aware", desc: "A face your audience already trusts. Borrowed authority stops the scroll." },
  { name: "Press",        emoji: "\uD83D\uDCF0", funnel: "Product \u2192 Most Aware", desc: "Logos, headlines, article screenshots. \u2018As seen in Vogue, Forbes, GQ.\u2019" },
  { name: "Social Proof Mashup", emoji: "\uD83D\uDCAC", funnel: "Product \u2192 Most Aware", desc: "Many pieces of proof cut fast: UGC, reviews, ratings, press logos, before & afters." },
  { name: "Montage",      emoji: "\uD83C\uDF9E\uFE0F", funnel: "Product \u2192 Most Aware", desc: "Many shots cut fast. Breadth without any single moment carrying the load." },
  { name: "Cinematic B-Roll", emoji: "\uD83D\uDCFD\uFE0F", funnel: "Solution \u2192 Product", desc: "Beautifully shot moments of your product in use. Polish is the credibility." },
  { name: "ASMR",         emoji: "\uD83E\uDD2B", funnel: "Unaware \u2192 Problem", desc: "Show your product through sound: the tap, the crinkle, the pour, the squeeze." },
  { name: "Stop Motion",  emoji: "\u270B", funnel: "Unaware \u2192 Problem", desc: "Frame-by-frame animation. The craft of the motion is the hook." },
  { name: "Time Lapse",   emoji: "\u231B", funnel: "Problem \u2192 Product", desc: "Sped-up footage of a transformation. The fast-forward makes change feel inevitable." },
  { name: "Duet",         emoji: "\uD83D\uDC6F", funnel: "Unaware \u2192 Problem", desc: "Splitscreen with another video. Piggyback on a clip the algorithm is already pushing." },
  { name: "Stitch",       emoji: "\uD83E\uDEA1", funnel: "Unaware \u2192 Problem", desc: "The first seconds of someone else's video, then a cut to your reply." },
  { name: "Reaction",     emoji: "\uD83D\uDE32", funnel: "Unaware \u2192 Problem", desc: "Someone reacting in real time. Come for the face, stay for the context." },
  { name: "Grid Swap",    emoji: "\uD83D\uDFE6", funnel: "Solution \u2192 Product", desc: "Frame stays the same; one element swaps in and out. Your product is the one that fits." },
  { name: "Postit",       emoji: "\uD83D\uDCCC", funnel: "Solution \u2192 Product", desc: "Sticky notes around the product, each calling out a benefit. Scrappy and low-fi." },
  { name: "Behind The Scenes", emoji: "\uD83C\uDFAC", funnel: "Problem \u2192 Solution", desc: "Show the part of the brand the audience never sees: how it's made, who makes it." },
  { name: "Whiteboard Explainer", emoji: "\uD83D\uDC68\u200D\uD83C\uDFEB", funnel: "Unaware \u2192 Problem", desc: "A whiteboard, a marker and an explanation drawn out as you talk." },
  { name: "Humour",       emoji: "\uD83D\uDE02", funnel: "Unaware", desc: "Lead with the laugh, land the product on the punchline." },
  { name: "AI Generated", emoji: "\uD83E\uDD16", funnel: "Unaware \u2192 Problem", desc: "Imagery your camera couldn't capture. Surreal, impossible visuals for a fresh hook." },
  { name: "Pattern Interrupt", emoji: "\uD83E\uDD21", funnel: "Unaware \u2192 Problem", desc: "An opening with nothing obvious to do with the product. The job: stop the thumb." },
];
